### PR TITLE
Few changes

### PR DESCRIPTION
**Pull request by surajdazz**
Hey shreesha can you please merge these? Thanks!

### CODE REVIEW

**Comment by Shreeesha** [comment]
Have you tested them all before pushing? @surajdazz

**Comment by surajdazz** [comment]
Yes everything is fine!

**Comment by Shreeesha** [comment]
Fine then. Merging! Seems good additions to me

**Comment by surajdazz** [comment]
btw have you added some tweak that relaxs the GPU? i meanits stuck on 390mhz max frequency after a reboot

**Pull request merged**
